name: Deploy
on: [pull_request, push, workflow_dispatch]

defaults:
  run:
    working-directory: apps/aura-design-docs

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # 用于 Deno Deploy 身份认证
      contents: read # 用于克隆仓库

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm
        
      - name: Install dependencies
        run: pnpm i

      - name: Build
        run: pnpm run build-storybook

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: aura-design
          entrypoint: https://deno.land/std@0.216.0/http/file_server.ts
          root: apps/aura-design-docs/storybook-static
